airdrink/airdrink/urls.py
# =============================================================================
# IMPORTS
# =============================================================================

from django.contrib import admin
from django.urls import include, path
from drinks.views import DrinkRecipeView, SearchDrinksView, index

# =============================================================================
# ROUTES
# =============================================================================


urlpatterns = [
    path("", index),
    # path("drinks/", DrinksView.as_view()),
    path("search/", SearchDrinksView.as_view(), name="drinks_search"),
    path("drink/<int:pk>/", DrinkRecipeView.as_view(), name="recipe_view"),
    path("api/", include("drinks.urls")),
    path("admin/", admin.site.urls),
]

airdrink/drinks/urls.py
# -*- coding=utf-8 -*-

# =============================================================================
# IMPORTS
# =============================================================================

from django.urls import include, path
from drinks.views import (
    AlcoholicViewSet,
    CategoryViewSet,
    DrinkViewSet,
    GlassViewSet,
    IngredientViewSet,
    RecipeViewSet,
)
from rest_framework import routers

# =============================================================================
# ROUTES
# =============================================================================

router = routers.DefaultRouter()
router.register(r"alcoholic", AlcoholicViewSet, basename="alcoholic")
router.register(r"category", CategoryViewSet, basename="category")
router.register(r"drink", DrinkViewSet, basename="drink")
router.register(r"glass", GlassViewSet, basename="glass")
router.register(r"ingredient", IngredientViewSet, basename="ingredient")
router.register(r"recipe", RecipeViewSet, basename="recipe")

urlpatterns = [
    path("", include(router.urls)),
]

airdrink/drinks/models/Alcoholic.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models

# =============================================================================
# MODEL
# =============================================================================


class Alcoholic(models.Model):
    """docstring for Alcoholic."""

    alcoholic = models.CharField(max_length=255)

    class Meta:
        ordering = ["alcoholic"]

    def __str__(self):
        return self.alcoholic

airdrink/drinks/models/Category.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models

# =============================================================================
# MODEL
# =============================================================================


class Category(models.Model):
    """docstring for Category."""

    category = models.CharField(max_length=255)

    class Meta:
        ordering = ["category"]

    def __str__(self):
        return self.category

airdrink/drinks/models/Drink.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models
from drinks.models.Alcoholic import Alcoholic
from drinks.models.Category import Category
from drinks.models.Glass import Glass

# =============================================================================
# MODEL
# =============================================================================


class Drink(models.Model):
    """docstring for Drink."""

    id_drink = models.CharField(max_length=255)
    drink = models.CharField(max_length=255)
    date_modified = models.DateTimeField(null=True, auto_now=True)
    fk_alcoholic = models.ForeignKey(
        Alcoholic,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    fk_category = models.ForeignKey(
        Category,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    thumbnail = models.TextField(null=True)
    fk_glass = models.ForeignKey(
        Glass,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    iba = models.TextField(null=True)
    instructions = models.TextField(null=True)
    video = models.TextField(null=True)

    class Meta:
        ordering = ["drink"]

    def __str__(self):
        return self.drink

airdrink/drinks/models/Glass.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models

# =============================================================================
# MODEL
# =============================================================================


class Glass(models.Model):
    """docstring for Glass."""

    glass = models.CharField(max_length=255)

    class Meta:
        ordering = ["glass"]

    def __str__(self):
        return self.glass

airdrink/drinks/models/Ingredient.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models

# =============================================================================
# MODEL
# =============================================================================


class Ingredient(models.Model):
    """docstring for Ingredient."""

    ingredient = models.CharField(max_length=255)

    class Meta:
        ordering = ["ingredient"]

    def __str__(self):
        return self.ingredient

airdrink/drinks/models/Recipe.py
# coding=utf-8

# =============================================================================
# IMPORTS
# =============================================================================


from django.db import models
from drinks.models.Drink import Drink
from drinks.models.Ingredient import Ingredient

# =============================================================================
# MODEL
# =============================================================================


class Recipe(models.Model):
    """docstring for Recipe."""

    fk_drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    fk_ingredient = models.ForeignKey(
        Ingredient,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    measure = models.CharField(max_length=255, null=True)

airdrink/drinks/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet"
        href="{% static 'bootstrap-5.0.0-beta3-dist/css/bootstrap.css' %}">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Air Drink</a>
            <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/api">API</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}{% endblock %}
    </main>


</body>


<script
    src="{% static 'bootstrap-5.0.0-beta3-dist/js/bootstrap.js' %}"></script>

</html>

airdrink/drinks/templates/index.html
{% extends 'base.html'%}

{% block content %}

<h1>Welcome</h1>

<p>
    <a class="btn btn-success" href="/search">Search</a>
    <a class="btn btn-primary" href="/admin">Admin</a>
    <a class="btn btn-warning" href="/api">API</a>
</p>

{% endblock %}

airdrink/drinks/templates/recipe.html
{% extends "base.html"%}

{% block content %}

<div class="row">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/search/?q={{ drink.drink }}">Search</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ drink.drink }}</li>
    </ol>
  </nav>
</div>

<h1>{{ drink.drink }}</h1>
<p>Update: {{ drink.date_modified }}</p>

<p><img src="{{ drink.thumbnail }}" width=100 height=100 class="img-thumbnail" alt="{{ drink.drink }}"></p>

<table class="table table-bordered table-hover">
  <tr>
    <td><b>Alcoholic</b></td>
    <td>{{ drink.fk_alcoholic }}</td>
  </tr>
  <tr>
    <td><b>Category</b></td>
    <td>{{ drink.fk_category }}</td>
  </tr>
  <tr>
    <td><b>Glass</b></td>
    <td>{{ drink.fk_glass }}</td>
  </tr>
  <tr>
    <td><b>IBA</b></td>
    <td>{{ drink.iba }}</td>
  </tr>
</table>

<br><br>

<h2>Ingredients</h2>

<div class="row">
  <ul class="list-group">
    {% for recipe in drink.recipe_set.all %}
        <li class="list-group-item">{{ recipe.measure }} {{ recipe.fk_ingredient }}</li>
    {% endfor %}
  </ul>
<div>

<br><br>

<h2>Recipe</h2>

<p>{{ drink.instructions }}</p>

<br><br>

<h2>Others</h2>

<p>Similar drinks</p>

<br><br>

{% endblock %}

airdrink/drinks/templates/search.html
{% extends "base.html"%}

{% block content %}

<h1>Search drinks</h1>

<form action="{% url "drinks_search" %}" method="get">
  <div class="mb-3">
    <label for="inputDrink" class="form-label">Cocktail name</label>
    <input name="q" type="text" class="form-control" id="inputDrink" aria-describedby="drinkHelp" placeholder="Mojito">
    <div id="drinkHelp" class="form-text">Search for your favorite cocktail or ingredient !</div>
  </div>
</form>

<br>

Drinks found: {{ object_list.count }}

<br>

<div class="list-group">
    {% for object in object_list %}
      <a href="/drink/{{ object.id }}" class="list-group-item list-group-item-action">{{ object.drink }} ({{ object.recipe_set.all.count }} ingredients)</a>
    {% empty %}
    <p>No drinks found.</p>
    {% endfor %}
</div>

{% endblock %}